### ISSUE TITLE
Project auto-switching not working

### ISSUE THREAD

**Issue by joeldbirch** [subhaze/sublime_codekit#1]
This is the package that had to happen, thanks!

It seems that project auto-switching is not working for me, although I can switch by selecting "Codekit: select project from view" via the command panel. All other features seem to work great.

Sorry, I'm not sure what info you need from me to demonstrate the issue further. Please let me know.

**Comment by subhaze** [comment]
@joeldbirch it's been awhile :) but, I was able to consistently recreate this issue with the current projects I had setup and fortunately it was a quick fix once I could replicate. Hopefully this solves the issues you were having too.

**Comment by joeldbirch** [comment]
Hello, thanks for this. I'm going to try it out again. Cheers!

**Comment by joeldbirch** [comment]
Just noticed this issue is still open. I should have returned to confirm that this issue was fixed. Thanks!
