### ISSUE TITLE
Opening new Sublime Text window launches Codekit

### ISSUE THREAD

**Issue by joeldbirch** [subhaze/sublime_codekit#10]
Hello,

I'm finding that Codekit launches in the background if I merely open a new Sublime Text window, unrelated to any Codekit project. Sometimes Codekit launches when I unfocus that window. I basically can't keep Codekit quitted. I guess this package may be causing it. Attached is an animated gif showing the issue.

![codekit-launches](https://cloud.githubusercontent.com/assets/75602/13516661/5b2fcce2-e210-11e5-9812-93c9e60e6449.gif)

**Comment by subhaze** [comment]
I think this has to do with the auto project switching for CodeKit. I'd say if you turn that feature off this shouldn't happen.

This is a bug though, as it shouldn't try to switch if there is no project. I'll look into this.

**Comment by subhaze** [comment]
Fixed in todays push
