### ISSUE TITLE
Sublime support bogus

### ISSUE THREAD

**Issue by anyotherway** [subhaze/sublime_codekit#14]
_Sublime support documentation sucks, absolutely_ looks like another Atom bleed-out, going after the cognitive artery. Proof in useless link: https://packagecontrol.io/packages/CodeKit%20Commands
**Manually Pausing CodeKit**

> "Info: More details about why it's good practice to pause and other critical things to know about CodeKit can be found here."

'here' goes to http://incident57.com/codekit/help.html#critical-things where the words "pause" or "pausing" not present, nor even relevant.
Review reads: "Now you too can lose your code, just like iTunes disappears your precious gems of music. In just one brainless installation!" Another poorly considered rush to completion.

**Comment by subhaze** [comment]
@anyotherway I'm not quite clear on what your issue is... I do need to read through the docs as there may be some instance where it states auto-pausing is enabled, but, I disabled it by default per the request of CodeKit's developer.

**Comment by subhaze** [comment]
@anyotherway OK, the new release of CodeKit came with a new site release, which broke the links.

@anyotherway next time you feel to take the time to report an issue, why not actually help fix things than bring toxic responses to OSS like you have above.
