### ISSUE TITLE
Enable project on auto-switch

### ISSUE THREAD

**Issue by redgluten** [subhaze/sublime_codekit#3]
Following Codekit's autor recommendations I try to keep most projects I’m not currently working on disabled in order to spare resources. Currently the plugin doesn’t enable the project in Codekit when it the switch is triggered, it would be a nice addition IMO.

**Comment by subhaze** [comment]
@bdkjones is this still relevant with version 3?

**Comment by bdkjones** [comment]
The plan is to add an AppleScript API for introspection of current projects, including paths, their enabled/disabled state etc. Once that's in place you could query the app to see if the project is enabled and, if not, enable it.

**Comment by subhaze** [comment]
OK, thanks for the feedback!
