### ISSUE TITLE
Enable/disable plugin on a per project basis

### ISSUE THREAD

**Issue by redgluten** [subhaze/sublime_codekit#8]
First thanks a lot for the great work. I really find it useful on my everyday work.

On certain projects I’m not able to use Codekit because I have to use the Grunt or Gulp team workflow so it would be handy to be able to tell Sublime Text to disable the plugin for this specific project.

Now : is it a Sublime Text feature or a sublime_codekit feature? I’m not sure but I guess you do. :)

**Comment by subhaze** [comment]
This should be fixed via commit https://github.com/subhaze/sublime_codekit/commit/426afb6b69a476a985ddae471d1e6ebc041b36f5 (forgot to add this issue to commit)
