### ISSUE TITLE
Can't remove codekit.config from a project

### ISSUE THREAD

**Issue by tschofen** [subhaze/sublime_codekit#9]
I want to remove codekit processing from a project. As I can't turn off codekit command on a project/directory, I thought removing the codekit.config file would do it. When I remove the codekit.config file from the project directory, (after quitting codekit and sublime) the file is recreated the next time I open sublime and switch out of it, which in turn opens codekit.

**Comment by subhaze** [comment]
This plugin doesn't create a `codekit.config` file. Just deleting the file doesn't remove it from CodeKit as it will still have a reference to that folder (you'll need to open CodeKit and remove the project as well) and when it doesn't see a config file in that folder it will create a new one.
